import type { Registration, RegistrationEvent } from "@/types";

const now = new Date();
const year = now.getFullYear();
const iso = (value: string) => new Date(value).toISOString();

export const demoEvents: RegistrationEvent[] = [
  {
    id: "7f317a6a-b7de-4b56-9fb7-00f41e1cb001",
    slug: "engineering-career-discovery-day",
    title: "Engineering Career Discovery Day",
    summary: "Meet practicing engineers and explore the disciplines shaping tomorrow.",
    description:
      "Spend an afternoon with Texas A&M engineering organizations and industry guests. Choose the session that works best for you, then complete the short registration form.",
    location: "Zachry Engineering Education Complex",
    startAt: iso(`${year + 1}-03-04T11:30:00-06:00`),
    endAt: iso(`${year + 1}-03-04T15:50:00-06:00`),
    registrationOpenAt: iso(`${year}-10-01T08:00:00-05:00`),
    registrationCloseAt: iso(`${year + 1}-03-02T23:59:00-06:00`),
    status: "published",
    capacityMode: "slot",
    capacity: null,
    sortOrder: 1,
    accentColor: "#7d1735",
    formFields: [
      { id: "classification", label: "Classification", type: "select", required: true, options: ["Freshman", "Sophomore", "Junior", "Senior", "Graduate"] },
      { id: "major", label: "Major", type: "short_text", required: true, placeholder: "e.g. Mechanical Engineering" },
      { id: "interests", label: "Disciplines you want to explore", type: "multiselect", required: false, options: ["Aerospace", "Civil", "Computer Science", "Electrical", "Industrial", "Mechanical"] },
      { id: "accommodations", label: "Accessibility or dietary accommodations", type: "long_text", required: false },
    ],
    confirmationSubject: "You're registered for {{event}}",
    confirmationBody: "Howdy {{firstName}}! Your registration is confirmed. Please show this email to the SEC volunteer at the room entrance.",
    slots: [
      {
        id: "slot-discovery-1130",
        label: "Morning session",
        startAt: iso(`${year + 1}-03-04T11:30:00-06:00`),
        endAt: iso(`${year + 1}-03-04T12:20:00-06:00`),
        location: "ZACH 340",
        capacity: 40,
        accentColor: "#7d1735",
        confirmationSubject: "Your 11:30 session is confirmed",
        confirmationBody: "Howdy {{firstName}}! Please show this confirmation at the entrance. Your {{event}} session begins at {{time}} in {{room}}.",
        registeredCount: 26,
        remaining: 14,
      },
      {
        id: "slot-discovery-1350",
        label: "Early afternoon session",
        startAt: iso(`${year + 1}-03-04T13:50:00-06:00`),
        endAt: iso(`${year + 1}-03-04T14:40:00-06:00`),
        location: "ZACH 420",
        capacity: 40,
        accentColor: "#d6a84b",
        registeredCount: 32,
        remaining: 8,
      },
      {
        id: "slot-discovery-1500",
        label: "Late afternoon session",
        startAt: iso(`${year + 1}-03-04T15:00:00-06:00`),
        endAt: iso(`${year + 1}-03-04T15:50:00-06:00`),
        location: "ZACH 420",
        capacity: 40,
        accentColor: "#49796b",
        registeredCount: 17,
        remaining: 23,
      },
    ],
    registeredCount: 75,
    remaining: null,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "7f317a6a-b7de-4b56-9fb7-00f41e1cb002",
    slug: "industry-night-aerospace",
    title: "Industry Night: Aerospace",
    summary: "An evening of conversation with leaders across the aerospace industry.",
    description: "Connect with recruiters and engineers, ask questions, and learn where an engineering degree can take you.",
    location: "Memorial Student Center, Bethancourt Ballroom",
    startAt: iso(`${year + 1}-01-22T18:00:00-06:00`),
    endAt: iso(`${year + 1}-01-22T20:00:00-06:00`),
    registrationOpenAt: iso(`${year}-10-01T08:00:00-05:00`),
    registrationCloseAt: iso(`${year + 1}-01-20T17:00:00-06:00`),
    status: "published",
    capacityMode: "event",
    capacity: 180,
    sortOrder: 2,
    accentColor: "#500000",
    formFields: [
      { id: "major", label: "Major", type: "short_text", required: true },
      { id: "resume", label: "Would you like a resume review?", type: "radio", required: true, options: ["Yes", "No"] },
    ],
    confirmationSubject: "Registration confirmed: {{event}}",
    confirmationBody: "Howdy {{firstName}}! We look forward to seeing you at {{event}} on {{date}}. Doors open 15 minutes early.",
    slots: [],
    registeredCount: 126,
    remaining: 54,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "7f317a6a-b7de-4b56-9fb7-00f41e1cb004",
    slug: "resume-review-studio",
    title: "Resume Review Studio",
    summary: "Bring a draft and leave with clearer feedback from engineers and recruiters.",
    description: "Drop in for focused resume feedback from industry partners and SEC volunteers. Bring a printed copy or a shareable draft.",
    location: "ZACH 525",
    startAt: iso(`${year + 1}-03-25T16:00:00-05:00`),
    endAt: iso(`${year + 1}-03-25T18:30:00-05:00`),
    registrationOpenAt: iso(`${year + 1}-01-15T08:00:00-06:00`),
    registrationCloseAt: iso(`${year + 1}-03-24T17:00:00-05:00`),
    status: "published",
    capacityMode: "event",
    capacity: 72,
    sortOrder: 3,
    accentColor: "#49796b",
    formFields: [{ id: "major", label: "Major", type: "short_text", required: true }, { id: "review_focus", label: "What would you like feedback on?", type: "select", required: true, options: ["First resume", "Internship search", "Full-time search", "Graduate school"] }],
    confirmationSubject: "You're booked for Resume Review Studio",
    confirmationBody: "Howdy {{firstName}}! Your Resume Review Studio spot is confirmed. Please bring a current resume draft.",
    slots: [],
    registeredCount: 39,
    remaining: 33,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "7f317a6a-b7de-4b56-9fb7-00f41e1cb005",
    slug: "aggie-coding-sprint",
    title: "Aggie Coding Sprint",
    summary: "A collaborative evening of small builds, code reviews, and practical problem solving.",
    description: "Form a team or arrive solo for an approachable campus coding sprint. Mentors will be available throughout the event.",
    location: "ZACH 340",
    startAt: iso(`${year + 1}-04-09T18:00:00-05:00`),
    endAt: iso(`${year + 1}-04-09T21:00:00-05:00`),
    registrationOpenAt: iso(`${year + 1}-02-01T08:00:00-06:00`),
    registrationCloseAt: iso(`${year + 1}-04-08T17:00:00-05:00`),
    status: "published",
    capacityMode: "event",
    capacity: 100,
    sortOrder: 4,
    accentColor: "#355e92",
    formFields: [{ id: "experience", label: "Programming experience", type: "select", required: true, options: ["New to coding", "Some coursework", "Comfortable building projects", "Advanced"] }, { id: "team", label: "Do you already have a team?", type: "radio", required: true, options: ["Yes", "No, match me with one"] }],
    confirmationSubject: "Registration confirmed: Aggie Coding Sprint",
    confirmationBody: "Howdy {{firstName}}! Your place at Aggie Coding Sprint is confirmed. Bring a laptop and charger.",
    slots: [],
    registeredCount: 61,
    remaining: 39,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "7f317a6a-b7de-4b56-9fb7-00f41e1cb006",
    slug: "engineering-leadership-forum",
    title: "Engineering Leadership Forum",
    summary: "Hear how alumni lead technical teams, make decisions, and build careers with range.",
    description: "A moderated conversation with Aggie alumni across engineering disciplines, followed by small-group questions and networking.",
    location: "MSC 2300A",
    startAt: iso(`${year + 1}-05-01T17:30:00-05:00`),
    endAt: iso(`${year + 1}-05-01T19:30:00-05:00`),
    registrationOpenAt: iso(`${year + 1}-02-15T08:00:00-06:00`),
    registrationCloseAt: iso(`${year + 1}-04-30T17:00:00-05:00`),
    status: "published",
    capacityMode: "unlimited",
    capacity: null,
    sortOrder: 5,
    accentColor: "#a6752d",
    formFields: [{ id: "major", label: "Major", type: "short_text", required: true }, { id: "question", label: "A question for the panel", type: "long_text", required: false }],
    confirmationSubject: "You're registered for Engineering Leadership Forum",
    confirmationBody: "Howdy {{firstName}}! We look forward to seeing you at Engineering Leadership Forum.",
    slots: [],
    registeredCount: 87,
    remaining: null,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "7f317a6a-b7de-4b56-9fb7-00f41e1cb003",
    slug: "spark-stem-day",
    title: "SPARK STEM Day",
    summary: "Hands-on engineering activities for visiting middle school students.",
    description: "A full day of guided challenges led by SEC volunteers.",
    location: "Zachry Engineering Education Complex",
    startAt: iso(`${year - 1}-04-12T09:00:00-05:00`),
    endAt: iso(`${year - 1}-04-12T15:00:00-05:00`),
    registrationOpenAt: iso(`${year - 1}-01-15T08:00:00-06:00`),
    registrationCloseAt: iso(`${year - 1}-04-05T23:59:00-05:00`),
    status: "published",
    capacityMode: "event",
    capacity: 120,
    sortOrder: 6,
    accentColor: "#9f6b30",
    formFields: [{ id: "school", label: "School", type: "short_text", required: true }],
    confirmationSubject: "SPARK STEM Day registration",
    confirmationBody: "Howdy {{firstName}}! Your place at {{event}} is confirmed.",
    slots: [],
    registeredCount: 118,
    remaining: 2,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
];

export const demoRegistrations: Registration[] = [
  {
    id: "demo-registration-1",
    eventId: demoEvents[2].id,
    slotId: null,
    firstName: "Reveille",
    lastName: "Student",
    email: "student@tamu.edu",
    uin: "123456789",
    answers: { school: "A&M Consolidated" },
    status: "confirmed",
    emailStatus: "delivered",
    createdAt: iso(`${year - 1}-02-02T14:15:00-06:00`),
  },
];
