import type { Registration, RegistrationEvent } from "@/types";

const now = new Date();
const year = now.getFullYear();
const iso = (value: string) => new Date(value).toISOString();

export const demoEvents: RegistrationEvent[] = [
  {
    id: "7f317a6a-b7de-4b56-9fb7-00f41e1cb001",
    slug: "engineering-career-discovery-day",
    title: "Engineering Career Discovery Day",
    summary: "Meet practicing engineers and explore the disciplines shaping tomorrow.",
    description:
      "Spend an afternoon with Texas A&M engineering organizations and industry guests. Choose the session that works best for you, then complete the short registration form.",
    location: "Zachry Engineering Education Complex",
    startAt: iso(`${year + 1}-03-04T11:30:00-06:00`),
    endAt: iso(`${year + 1}-03-04T15:50:00-06:00`),
    registrationOpenAt: iso(`${year}-10-01T08:00:00-05:00`),
    registrationCloseAt: iso(`${year + 1}-03-02T23:59:00-06:00`),
    status: "published",
    capacityMode: "slot",
    capacity: null,
    sortOrder: 1,
    accentColor: "#7d1735",
    formFields: [
      { id: "classification", label: "Classification", type: "select", required: true, options: ["Freshman", "Sophomore", "Junior", "Senior", "Graduate"] },
      { id: "major", label: "Major", type: "short_text", required: true, placeholder: "e.g. Mechanical Engineering" },
      { id: "interests", label: "Disciplines you want to explore", type: "multiselect", required: false, options: ["Aerospace", "Civil", "Computer Science", "Electrical", "Industrial", "Mechanical"] },
      { id: "accommodations", label: "Accessibility or dietary accommodations", type: "long_text", required: false },
    ],
    confirmationSubject: "You're registered for {{event}}",
    confirmationBody: "Howdy {{firstName}}! Your registration is confirmed. Please show this email to the SEC volunteer at the room entrance.",
    slots: [
      {
        id: "slot-discovery-1130",
        label: "Morning session",
        startAt: iso(`${year + 1}-03-04T11:30:00-06:00`),
        endAt: iso(`${year + 1}-03-04T12:20:00-06:00`),
        location: "ZACH 340",
        capacity: 40,
        accentColor: "#7d1735",
        confirmationSubject: "Your 11:30 session is confirmed",
        confirmationBody: "Howdy {{firstName}}! Please show this confirmation at the entrance. Your {{event}} session begins at {{time}} in {{room}}.",
        registeredCount: 26,
        remaining: 14,
      },
      {
        id: "slot-discovery-1350",
        label: "Early afternoon session",
        startAt: iso(`${year + 1}-03-04T13:50:00-06:00`),
        endAt: iso(`${year + 1}-03-04T14:40:00-06:00`),
        location: "ZACH 420",
        capacity: 40,
        accentColor: "#d6a84b",
        registeredCount: 32,
        remaining: 8,
      },
      {
        id: "slot-discovery-1500",
        label: "Late afternoon session",
        startAt: iso(`${year + 1}-03-04T15:00:00-06:00`),
        endAt: iso(`${year + 1}-03-04T15:50:00-06:00`),
        location: "ZACH 420",
        capacity: 40,
        accentColor: "#49796b",
        registeredCount: 17,
        remaining: 23,
      },
    ],
    registeredCount: 75,
    remaining: null,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "7f317a6a-b7de-4b56-9fb7-00f41e1cb002",
    slug: "industry-night-aerospace",
    title: "Industry Night: Aerospace",
    summary: "An evening of conversation with leaders across the aerospace industry.",
    description: "Connect with recruiters and engineers, ask questions, and learn where an engineering degree can take you.",
    location: "Memorial Student Center, Bethancourt Ballroom",
    startAt: iso(`${year + 1}-01-22T18:00:00-06:00`),
    endAt: iso(`${year + 1}-01-22T20:00:00-06:00`),
    registrationOpenAt: iso(`${year}-10-01T08:00:00-05:00`),
    registrationCloseAt: iso(`${year + 1}-01-20T17:00:00-06:00`),
    status: "published",
    capacityMode: "event",
    capacity: 180,
    sortOrder: 2,
    accentColor: "#500000",
    formFields: [
      { id: "major", label: "Major", type: "short_text", required: true },
      { id: "resume", label: "Would you like a resume review?", type: "radio", required: true, options: ["Yes", "No"] },
    ],
    confirmationSubject: "Registration confirmed: {{event}}",
    confirmationBody: "Howdy {{firstName}}! We look forward to seeing you at {{event}} on {{date}}. Doors open 15 minutes early.",
    slots: [],
    registeredCount: 126,
    remaining: 54,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "7f317a6a-b7de-4b56-9fb7-00f41e1cb003",
    slug: "spark-stem-day",
    title: "SPARK STEM Day",
    summary: "Hands-on engineering activities for visiting middle school students.",
    description: "A full day of guided challenges led by SEC volunteers.",
    location: "Zachry Engineering Education Complex",
    startAt: iso(`${year - 1}-04-12T09:00:00-05:00`),
    endAt: iso(`${year - 1}-04-12T15:00:00-05:00`),
    registrationOpenAt: iso(`${year - 1}-01-15T08:00:00-06:00`),
    registrationCloseAt: iso(`${year - 1}-04-05T23:59:00-05:00`),
    status: "published",
    capacityMode: "event",
    capacity: 120,
    sortOrder: 3,
    accentColor: "#9f6b30",
    formFields: [{ id: "school", label: "School", type: "short_text", required: true }],
    confirmationSubject: "SPARK STEM Day registration",
    confirmationBody: "Howdy {{firstName}}! Your place at {{event}} is confirmed.",
    slots: [],
    registeredCount: 118,
    remaining: 2,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
];

export const demoRegistrations: Registration[] = [
  {
    id: "demo-registration-1",
    eventId: demoEvents[2].id,
    slotId: null,
    firstName: "Reveille",
    lastName: "Student",
    email: "student@tamu.edu",
    uin: "123456789",
    answers: { school: "A&M Consolidated" },
    status: "confirmed",
    emailStatus: "delivered",
    createdAt: iso(`${year - 1}-02-02T14:15:00-06:00`),
  },
];
